package main

import "testing"

func TestParseBLSEntry(t *testing.T) {
	cases := []struct {
		name       string
		body       string
		wantLinux  string
		wantInitrd string
	}{
		{
			name:       "well-formed entry",
			body:       "title bazzite\nlinux /EFI/bazzite/vmlinuz\ninitrd /EFI/bazzite/initrd.img\noptions root=LABEL=TBOX_STORE\n",
			wantLinux:  "/EFI/bazzite/vmlinuz",
			wantInitrd: "/EFI/bazzite/initrd.img",
		},
		{
			name:       "extra whitespace + tabs",
			body:       "title  Bazzite Live\nlinux\t/images/pxeboot/bazzite/vmlinuz\ninitrd  /images/pxeboot/bazzite/initrd.img\n",
			wantLinux:  "/images/pxeboot/bazzite/vmlinuz",
			wantInitrd: "/images/pxeboot/bazzite/initrd.img",
		},
		{
			name:       "missing linux line",
			body:       "title x\ninitrd /a\n",
			wantLinux:  "",
			wantInitrd: "/a",
		},
		{
			name:       "blank lines and comments are tolerated",
			body:       "\n# generated by tacklebox\n\nlinux /vmlinuz\ninitrd /initrd.img\n\n",
			wantLinux:  "/vmlinuz",
			wantInitrd: "/initrd.img",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := parseBLSEntry(tc.body)
			if got.linux != tc.wantLinux {
				t.Errorf("linux = %q, want %q", got.linux, tc.wantLinux)
			}
			if got.initrd != tc.wantInitrd {
				t.Errorf("initrd = %q, want %q", got.initrd, tc.wantInitrd)
			}
		})
	}
}

func TestCheckBLSResolves(t *testing.T) {
	files := map[string]bool{
		"EFI/bazzite/vmlinuz":    true,
		"EFI/bazzite/initrd.img": true,
		"loader/loader.conf":     true,
	}
	cases := []struct {
		name    string
		entry   blsEntry
		wantErr bool
	}{
		{
			name:    "both resolve",
			entry:   blsEntry{name: "ok.conf", linux: "/EFI/bazzite/vmlinuz", initrd: "/EFI/bazzite/initrd.img"},
			wantErr: false,
		},
		{
			name:    "linux missing",
			entry:   blsEntry{name: "bad.conf", linux: "/EFI/aurora/vmlinuz", initrd: "/EFI/bazzite/initrd.img"},
			wantErr: true,
		},
		{
			name:    "initrd missing",
			entry:   blsEntry{name: "bad.conf", linux: "/EFI/bazzite/vmlinuz", initrd: "/EFI/aurora/initrd.img"},
			wantErr: true,
		},
		{
			name:    "both empty",
			entry:   blsEntry{name: "empty.conf"},
			wantErr: true,
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			r := checkBLSResolves(tc.entry, files, "ESP")
			if (r.err != nil) != tc.wantErr {
				t.Errorf("got err=%v, wantErr=%v", r.err, tc.wantErr)
			}
		})
	}
}
